# Generated by Django 4.2.5 on 2023-10-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livros', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=255)),
                ('autor', models.TextField(max_length=255)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
